return {
  mason = {
    ensure_installed = {
      'tailwindcss-language-server',
      'yaml-language-server',
      'svelte-language-server',
      'astro-language-server',
      'gopls',
      'vtsls',
      'taplo',
      'json-lsp',
      'stylua',
      'vue-language-server',
      'prettierd',
      'eslint_d',
    },

    registries = {
      'github:mason-org/mason-registry',
    },
  },

  treesitter = {
    'vue',
    'angular',
    'scss',
    'typescript',
    'javascript',
    'astro',
    'svelte',
    'css',
    'html',
    'bash',
    'c',
    'c_sharp',
    'diff',
    'lua',
    'luadoc',
    'markdown',
    'markdown_inline',
    'query',
    'vim',
    'vimdoc',
    'rust',
    'ron',
    'regex',
    'php',
    'latex',
    'norg',
    'typst',
    'tsx',
  },
}
